// LOCAL HOST - GET CONTACTS
GET http://localhost:5000/contacts
###
GET http://localhost:5000/contacts/644abcbd9ba9cd0fc249af7a
###
GET http://localhost:5000/contacts/644abd949ba9cd0fc249af7b
###
GET http://localhost:5000/contacts/644abe419ba9cd0fc249af7c
###
GET http://localhost:5000/contacts/644abe909ba9cd0fc249af7d

// LOCAL HOST - CREATE NEW CONTACT
###
POST http://localhost:5000/contacts HTTP/1.1
Content-type: application/json

{
    "firstName":"Paige", 
    "lastName":"Brady", 
    "email":"brooke@fakeemail.com", 
    "favoriteColor":"purple", 
    "birthday":"05/02/2013"
}

// LOCAL HOST - UPDATE CONTACT
###
PUT http://localhost:5000/contacts/645565779c9662683609459e HTTP/1.1
Content-type: application/json

{
    "firstName":"Jack", 
    "lastName":"Brady", 
    "email":"jack@fakeemail.com", 
    "favoriteColor":"blue", 
    "birthday":"08/25/2016"
}

// LOCAL HOST - DELETE CONTACT
###
DELETE http://localhost:5000/contacts/6455528fd8d4a46098685bdf HTTP/1.1


// PRODUCTION (RENDER) DEPLOY - GET CONTACTS
###
GET https://cse341-spring23-dfu6.onrender.com/contacts
###
GET https://cse341-spring23-dfu6.onrender.com/contacts/644abcbd9ba9cd0fc249af7a
###
GET https://cse341-spring23-dfu6.onrender.com/contacts/644abd949ba9cd0fc249af7b
###
GET https://cse341-spring23-dfu6.onrender.com/contacts/644abe419ba9cd0fc249af7c
###
GET https://cse341-spring23-dfu6.onrender.com/contacts/645564ad9c9662683609459d

// PRODUCTION (RENDER) DEPLOY - CREATE NEW CONTACT
###
POST https://cse341-spring23-dfu6.onrender.com/contacts HTTP/1.1
Content-type: application/json

{
    "firstName":"TEST", 
    "lastName":"ONE", 
    "email":"TEST@fakeemail.com", 
    "favoriteColor":"TEST", 
    "birthday":"12/03/1978"
}

// PRODUCTION (RENDER) DEPLOY - UPDATE CONTACT
###
PUT https://cse341-spring23-dfu6.onrender.com/contacts/6455a907ea3259b5cd9f585a HTTP/1.1
Content-type: application/json

{
    "firstName":"Paige", 
    "lastName":"Brady", 
    "email":"paige@fakeemail.com", 
    "favoriteColor":"pink", 
    "birthday":"03/11/2015"
}

// PRODUCTION (RENDER) DEPLOY - DELETE CONTACT
###
DELETE https://cse341-spring23-dfu6.onrender.com/contacts/64555d88a1e87bfad909c72e HTTP/1.1